# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Learning to see
email: logmister@gmail.com
owner: Logan Pendergrass
description: > # this means to ignore newlines until "baseurl:"
  The portfolio of Logan Pendergrass : Learning to see, one project at a time
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
fb_url: logan.pendergrass
twitter_username: ljp_206
github_username: ljpendergrass
codepen_username: djmankiewicz


# Build settings
markdown: kramdown
